### ISSUE TITLE
tcl-tk should be optional

### ISSUE THREAD

**Issue by TomSnijders** [snlab-nl/rsiena#1]
In the first ever  R-CMD-check of RSiena on GitHub, there was a failure for the Mac. 
I think this relates to the message I received from Brian Ripley May 4th:

<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>
'Writing R Extensions' has warned for years that Tktable is no longer widely available (it was last updated in 2008 and has been removed from e.g. Fedora).  It is no longer distributed with R 4.0.0 on Windows and is intended to be removed on macOS (that intention was originally for R
4.0.0 but Tcl/Tk has not yet been updated there).
Your choices would appear to be
- no longer make use of it
- check it it is available, and only use it if it is.
- agree amongst yourselves to provide an R package which provides it and puts it on the Tcl/Tk search path, and to depend on that package.
<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>

I plan to take tcltk out of "Imports", probably move it to "suggests", and use require(tcltk) or some such as a condition for opening the Siena gui during operation of siena07.

**Comment by jhollway** [comment]
How critical is a Tktable based gui nowadays? We could instead offer a more verbose console reporting system for teaching purposes and for those who want to see RSiena "in action"? Or are there other dependencies?

**Comment by perblock** [comment]
I sometimes use the gui to speed up estimation for rough guesstimates (using end phase 2) and convergence (restarting after subphase 2). So I think the gui helps

**Comment by TomSnijders** [comment]
I find the gui essential for my own use. I use it to monitor what happens in case of difficult convergence or divergence. Perhaps I can write something more about this in the manual. For the solution of this issue, my idea is to use
if require(tcltk)
and then force batch mode if tcltk is not available.
When I’m back from holidays, late July, this is one of the first things on my list.

Cheers,
Tom

=================================================
Tom A.B. Snijders
Professor of Statistics and Methodology
Department of Sociology, University of Groningen
Emeritus Fellow, Nuffield College, University of Oxford
Associate Member, Dept. of Statistics, University of Oxford

**Comment by jhollway** [comment]
Both uses make sense.

**Comment by jhollway** [comment]
@auzaheta, @stadtfeldethz mentioned you had been looking into this issue?

**Comment by auzaheta** [comment]
Not about tcltk. It's a change in the configure file regarding MPI, OpenMP, and C++ in the different operative systems (especially Mac). I'll open a new issue with the specification.

**Comment by jhollway** [comment]
Great, yes please raise this as another issue
