### ISSUE TITLE
Make constraints compatible with combination of directed - nondirected networks

### ISSUE THREAD

**Issue by TomSnijders** [snlab-nl/rsiena#10]
Constraints between networks do not explicitly take into account that one network might be symmetric and the other directed. This question came up in the context of an application, with specifically the use of the "disjoint" constraint.

Constraints are implemented in src/model/filters, and used in EpochSimulation with  addPermittedChangeFilter. (By the way, this seems to be a case of excellent and transparent programming.)

Steps to be taken:

1. Construct a test showing whether a constraint works for a combination of one directed and one symmetric network; first, for "disjoint".
2. Try it out for the current version; probably it does not work. If it does work, this issue will be closed.
3. Try to solve this by modifying the filter and the application of addPermittedChangeFilter. First, for "disjoint".
4. Do this also for the other filters.

**Comment by jhollway** [comment]
A test-related question: do we want to move to a `[testthat](https://testthat.r-lib.org)` testing framework?

**Comment by TomSnijders** [comment]
RSiena already contains \tests. Would testthat be additional to this?

**Comment by jhollway** [comment]
[`testthat`](https://testthat.r-lib.org) would operate in that same folder, but offers a pretty straightforward structure for unit testing (see [here](https://r-pkgs.org/tests.html)). It is used in very many packages, including [`goldfish`](https://github.com/snlab-ch/goldfish/blob/main/tests/testthat/test-functions_effects_DyNAM_choice-update_alter.R) and [`roctopus`](https://github.com/jhollway/roctopus/tree/main/tests). I believe it also offers ways to test C++ code [together with](https://testthat.r-lib.org/reference/use_catch.html) [catch](https://github.com/catchorg/Catch2). I _think_ trying it for this one use case won't break the existing tests, and then, if it works, we can slowly migrate over.

**Comment by TomSnijders** [comment]
Very good, could you please do this?

**Comment by jhollway** [comment]
I don't think I understand what the actual test should be yet:

1. which function is being tested here/can we run?
1. what output should it have if it is working as expected?

**Comment by TomSnijders** [comment]
I’m constructing a test now. The answer is not a single number or vector; well, perhaps it will be one. I’m thinking of it.

=================================================
Tom A.B. Snijders
Professor of Statistics and Methodology
Department of Sociology, University of Groningen
Emeritus Fellow, Nuffield College, University of Oxford
Associate Member, Dept. of Statistics, University of Oxford

**Comment by TomSnijders** [comment]
The filters for disjoint and higher were changed, to allow disjointness between a symmetric and a non-symmetric network; and to allow that a symmetric network is larger than (or equal to) a non-symmetric network. Corresponding changes were made to sienaDataCreate and sienaDataConstraint.
