### ISSUE TITLE
Migrate tests to testthat package

### ISSUE THREAD

**Issue by jhollway** [snlab-nl/rsiena#16]
As discussed at Duisterbelt 2020 with, among others, @TomSnijders @stadtfeldethz @auzaheta

**Comment by jhollway** [comment]
@TomSnijders @auzaheta I've added a basic structure here, but the tests are not currently running because the procedure seizes on an unexpected `read.csv("allEffects.csv")` call under `data/`. Perhaps we can work out another place for this data/information, such as in `inst/` if it needs to be available as such after building or in its own `data/*.rda` file if not?

**Comment by jhollway** [comment]
Indeed, another option is in `R/sysdata.rda`, which can be [called within functions](https://stackoverflow.com/questions/32964741/accessing-sysdata-rda-within-package-functions) without issues. We use it in other packages, e.g. `{[qStates](https://github.com/globalgov/qStates/tree/main/R)}`.

**Comment by TomSnijders** [comment]
I have for the moment dropped the dependence on testthat, and these tests. Tests now are done by running parallel.R and comparing the output with parallel.Rout.save. Tests may be added to parallel.R, of course; if other functionality for testing is desired, testthat can be reinstated.

**Comment by jhollway** [comment]
Ok, we can swing back around to testthat and unit testing at a later point if necessary. I'm therefore closing this issue.
