### ISSUE TITLE
Pushrelease for Windows should not have a directory layer

### ISSUE THREAD

**Issue by TomSnijders** [snlab-nl/rsiena#18]
**Zip file for windows binary contains superfluous directory structure.**
The binary zip file created by the pushrelease for installation on Windows contains the directory RSiena. This directory should not exist; the top level in the zip file should include the DESCRIPTION file etc.

**What to do**
Ah, the workflow files are so difficult to read and construct. I guess it is just a minor thing to drop the intermediate layer but how should this be done.

**Comment by TomSnijders** [comment]
I think this is solved now. However, I think still the zip file needs to be renamed to be accepted in Windows R for installation; how is that for the other two platforms?

**Comment by jhollway** [comment]
If it's solved, we can close the issue. The (named) downloaded packages install fine on Mac and should also on Linux ( see @stadtfeldethz ), but renaming the Windows one would mean that there's one binary that is not named with the OS. Alternatively, we could rename them all and just direct users to the binary with the correct suffix (`.zip`, `.tar.gz`, etc), but then we'd need to provide that information somewhere (on the README?).

**Comment by TomSnijders** [comment]
The executable for Windows now is called RSiena_winOS.zip. I tried to install that, which did not work, but renaming to RSiena.zip and also to RSiena_1.2.30.zip did the trick. I already noted this on http://www.stats.ox.ac.uk/~snijders/siena/siena_downloads.htm and in the manual.
So the only remaining thing is to wonder whether GitHub can give the constructed binary for Windows the name  RSiena.zip. When that is answered and, if positive, carried out, this issue can be closed.
