### ISSUE TITLE
NEWS.md needs proper structuring

### ISSUE THREAD

**Issue by jhollway** [snlab-nl/rsiena#2]
Need to follow [package guidelines](https://style.tidyverse.org/news.html) so that `pkgdown` builds site correctly

**Comment by TomSnijders** [comment]
My changes today to NEWS.md for version 1.2-32 were good, but I did not take into account the very useful recommendations of https://style.tidyverse.org/news.html. Something for next time.

**Comment by jhollway** [comment]
Indeed. Separating NEWS from ONEWS means we don't need to go back and restructure all previous news notes.
