### ISSUE TITLE
Failure of model for continuous behavior

### ISSUE THREAD

**Issue by TomSnijders** [snlab-nl/rsiena#25]
As was known earlier and bothering Nynke, there is an irreproducible bug when modeling continuous dependent behavior variables.  
What happened now is that yesterday and today, the checks for macOS went on very long. Yesterday they were automatically canceled by the system after 6 hours, today they were canceled by me after 3 hours. However, in between, when something else was changed (totally unrelated, the vignette), checks for macOS went OK.  All other checks were fine.   
This *seemed to* happen in the tests of parallel.R. My guess is that this was due to test16, which is for the continuous behavior model. I therefore temporarily disabled this test and all checks were fine now.
Clearly something irreproducible is the matter, and my guess is that this is related to the continuous behavior model - because that contains a known unknown error.

**Comment by jhollway** [comment]
Maybe set the random seed to one that we might expect runs/converges for all tests?

**Comment by TomSnijders** [comment]
No, that would be against the spirit of testing. 
Better let this bug bug us.

**Comment by TomSnijders** [comment]
I think the error was in a place where we did not look before. The call of `getEffects` in `initializeFRAN` should use the correct value of "onePeriodSde". This was done by giving effects objects this value as an attribute "onePeriodSde" and using that attribute when `getEffects` is called.   
As far as I can check, the model for continuous behavior variables now works without errors.
