### ISSUE TITLE
Convert Rscripts to markdown vignettes

### ISSUE THREAD

**Issue by jhollway** [snlab-nl/rsiena#5]
The scripts need to be downloaded from [the website](http://www.stats.ox.ac.uk/~snijders/siena/), saved as .Rmd files, and converted to R markdown, making sure not to run anything that requires user input outside of the script.

**Comment by TomSnijders** [comment]
We have done this now in RSiena 1.2-26. There is one basic vignette.
Is there anybody who thinks that the other four scripts in the \inst\scripts directory should be transformed into vignettes?

**Comment by jhollway** [comment]
You can up/downvote this issue using the emoticon icon in the top right of the original issue description.
