### ISSUE TITLE
Issue with adding multiple networks

### ISSUE THREAD

**Issue by jelkink** [snlab-nl/rsiena#64]
I had problems adding two networks to the same model. It appears indexing sparse matrices has changed since the code was written. The attached screenshot shows how I could fix the problem. It now seems to work fine.

![Screenshot 2023-03-22 100621](https://user-images.githubusercontent.com/11328/226869836-579ee42c-b9c7-403c-a2ce-1401f2c76f27.png)

**Comment by TomSnijders** [comment]
Thank you! I'm fixing this in the next update.

**Comment by csteglich** [comment]
Looks good, but it remains unclear to me what the sparse matrix issue may have been that causes the old code to fail. Probably this code runs faster, too.
