### ISSUE TITLE
avInSimDist2 effect

### ISSUE THREAD

**Issue by steffentriebel** [snlab-nl/rsiena#74]
I've tried coding the avInSimDist2 effect to catch up with the avAlt-family, for which the counterpart already exists.

I'm currently working on a manuscript revision that would greatly benefit from this effect, so would be grateful if someone could implement this.

**Comment by TomSnijders** [comment]
The avInSimDist2 and totInSimDist2 effects now are included in RSiena version 1.3.27. See the manual.

**Comment by steffentriebel** [comment]
Dear Tom,this is incredibly helpful for our R&R. I cannot thank you enough. I’ll now be able to specify a preliminary model without actor attributes to see if our findings still hold in a two-mode settings. If this gets published in the journal we’re working with right now, it is a career-making publication.Best wishesSteffenP.S.: I just left Durham today, where I visited Andrew Parker. He says hi!Am 01.10.2023 um 14:09 schrieb Tom Snijders ***@***.***>:﻿
The avInSimDist2 and totInSimDist2 effects now are included in RSiena version 1.3.27. See the manual.

**Comment by steffentriebel** [comment]
Obviously not meant to go to the GitHub repository, but also not too bad.

Hope everybody is doing fine :)

**Comment by Kaladani** [comment]
Thank you for implementing this effect already - it's a helpful stepping stone for other versions of indirect influence effects like adoption from structurally equivalent actors as well.

In the current manual, avInSimDist2 and totInSimDist2 are described two times (48., 49., 50. and 51. on page 194). 
I did not think it merits its own issue but could be an easy fix in the next Update of the Manual.

Best,
Daniel
