### ISSUE TITLE
intializeFRAN error after includeInteraction

### ISSUE THREAD

**Issue by yeahkyle** [snlab-nl/rsiena#75]
**Describe the bug**
I have recently updated my R (4.3.0) and RSiena (1.3.14), and now I get an error whenever I include an interaction.

The error which appears while trying to run siena07 is: "Error in initializeFRAN(z, x, initC = FALSE, ...) : 
  Cannot use standard initialisation with a different effect list"

The includeInteraction syntax that I am using is: 
eff2 <- includeInteraction(eff2, altX, altX, name="threat.net", interaction1=c("support_mi.net", "support_ipcloseness.net"), initialValue=0, include=T, type="eval")

The Algorithm is:
model <- sienaAlgorithmCreate(useStdInits=T, projname="Estimates.main",
                              nsub=4, n3=5000, maxlike=F, firstg=.03,
                              modelType=c(support.net=1,threat.net=1))

Everything works fine if I do not include any includeInteraction.

**Screenshots**

<img width="1033" alt="Screenshot 2023-06-21 at 3 56 56 PM" src="https://github.com/snlab-nl/rsiena/assets/14115413/5e14f580-7340-410d-82f4-6fe123214049">

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS Ventura 13.4]
 - R Version [e.g. 4.3.0]
 - RStudio Version [ 2023.03.1+446]

**Additional context**
This previously worked without any issues using RSiena 1.3.0.
Thank you!

**Comment by TomSnijders** [comment]
My first guess is that this was with an effects object created by a previous version of RSiena. There is no compatibility of effects objects between versions of RSiena. What happens when you create a new effects object?

**Comment by yeahkyle** [comment]
Thank you for the quick response, and for the public goods you continue to provide.

The effects object is created in the script, not stored from a previous version. That is, I load the data from csv files, then create separate objects for each covariate, then aggregate using sienaDataCreate, generate an effects object using getEffects, and then use includeEffects and includeInteractions. This used to work fine before updating R and RSiena (from 1.3.0)

The effects dataframe looks like I would expect, and the estimation works as long as I don't use includeInteractions. It also works if I generate the interactions as a multiplicative product of the two variables (prior to using sienaDatacreate) and include as a nodal covariate. This latter workaround can suffice for now if you are not seeing any bugs on your end.

Thank you,
Kyle

________________________________

**Comment by TomSnijders** [comment]
My second guess is that you used getEffects with specific values for one or more of the parameters nintn, behNintn, or onePeriodSde. 
If that was not the case, could you please send me (by email outside of GitHub) a data set and script for which the error occurs (perhaps after taking out some parts to get something limited in size and which you are willing to send). 
Your workaround seems fine to me.

**Comment by TomSnijders** [comment]
Kyle sent me a data set and script for which the error occurs. It turned out that the reason was that one of the dependent networks had a period in which ties did not decrease; the "uponly" case. This should be notified to the user in sienaDataCreate. The bug is that it is noted only for the last dependent variable. I will change (in the develop branch, later to be merged with the main) this by putting the place where the notification is made earlier in the code.

**Comment by TomSnijders** [comment]
There was one more error behind this issue. In `initializeFRAN`, when `x$useStdInits`, a comparison is made between the given effects object and the default effects object, to ensure the initial values are put in the proper places. This comparison is based on `effectName`, but these are changed for interaction effects. Therefore this is replaced by a comparison based on `shortName`.

**Comment by TomSnijders** [comment]
The errors were corrected in Version 1.3.23 by appropriate changes in `initializeFRAN`.
